export const BUCKET_TYPES = {
    MULTIPLY_2X: '2x',
    INTEREST_10_PERCENT: '+10%',
    INTEREST_20_PERCENT: '+20%',
    PENALTY_15_PERCENT: '-15%',
    BANKRUPT: '👹',
} as const;

export type BucketType = typeof BUCKET_TYPES[keyof typeof BUCKET_TYPES] | number;

export const BUCKET_POINTS = {
    [BUCKET_TYPES.MULTIPLY_2X]: -1000,
    [BUCKET_TYPES.INTEREST_10_PERCENT]: -1001,
    [BUCKET_TYPES.INTEREST_20_PERCENT]: -1002,
    [BUCKET_TYPES.PENALTY_15_PERCENT]: -1003,
    [BUCKET_TYPES.BANKRUPT]: -5000,
} as const;

export const ALL_BUCKET_TYPES: BucketType[] = [
    100, 200, 300, 50, -50, -100, -200,
    BUCKET_TYPES.MULTIPLY_2X,
    BUCKET_TYPES.INTEREST_10_PERCENT,
    BUCKET_TYPES.INTEREST_20_PERCENT,
    BUCKET_TYPES.PENALTY_15_PERCENT,
    BUCKET_TYPES.BANKRUPT
]
